// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  textbook: [
    {
      type: 'autogenerated',
      dirName: 'chapter-1-introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-2-foundations',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-3-human-design',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-4-perception',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-5-ai-control',
    },
    {
      type: 'autogenerated',
      dirName: 'chapter-6-locomotion',
    },
  ],
};

export default sidebars;
